name: Build and Publish Docker Image

permissions: write-all

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Build and Publish Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: yutanakamizo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ghcr.io/yutanakamizo/twspaces-notifier-api
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

